name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  # DEV Deployment Job
  Dev:
    environment: dev
    runs-on: ubuntu-latest
    
    steps:
      
      - name: My First Action
        run: echo "Hello Action"

  
